# Generated by Django 2.0.3 on 2018-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactusa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(auto_now_add=True, null='True')),
                ('Full_Name', models.CharField(max_length=300)),
                ('Email', models.CharField(max_length=300)),
                ('Phone_Number', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Type_of_Project', models.CharField(max_length=300)),
                ('Estimated_budget', models.CharField(max_length=300)),
                ('Tell_Us_About_Your_Project', models.CharField(max_length=300)),
            ],
        ),
    ]
